# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DrugCandidate.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class DrugCandidateSourceType(betterproto.Enum):
    UNKNOWN = 0
    MODEL = 1
    DATASET = 2
    USER = 3
    PAPER = 4
    EXPERIMENT = 5
    SIFTER = 6


@dataclass(eq=False, repr=False)
class DrugCandidate(betterproto.Message):
    # Metadata
    name: str = betterproto.string_field(1)
    key: str = betterproto.string_field(2)
    smiles: str = betterproto.string_field(3)
    # Scores
    drug_score: float = betterproto.double_field(4)
    safety_score: float = betterproto.double_field(5)
    manufacturability_score: float = betterproto.double_field(6)
    # Properties
    mass: float = betterproto.double_field(7)
    logp: float = betterproto.double_field(8)
    hydrogen_acceptors: int = betterproto.uint32_field(9)
    hydrogen_donors: int = betterproto.uint32_field(10)
    targets: List["DrugCandidateTarget"] = betterproto.message_field(11)
    sources: List["DrugCandidateSource"] = betterproto.message_field(12)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class DrugCandidateTarget(betterproto.Message):
    name: str = betterproto.string_field(1)
    affinity: float = betterproto.double_field(2)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class DrugCandidateSource(betterproto.Message):
    name: str = betterproto.string_field(1)
    type: "DrugCandidateSourceType" = betterproto.enum_field(2)
    version: int = betterproto.uint32_field(3)
    uri: str = betterproto.string_field(4)

    def __post_init__(self) -> None:
        super().__post_init__()
