# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DrugCandidate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DrugCandidate.proto',
  package='keter',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x44rugCandidate.proto\x12\x05keter\"\xd0\x03\n\rDrugCandidate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0e\n\x06smiles\x18\x03 \x01(\t\x12\x12\n\ndrug_score\x18\x04 \x01(\x01\x12\x14\n\x0csafety_score\x18\x05 \x01(\x01\x12\x1f\n\x17manufacturability_score\x18\x06 \x01(\x01\x12,\n\x07targets\x18\x07 \x03(\x0b\x32\x1b.keter.DrugCandidate.Target\x12,\n\x07sources\x18\x08 \x03(\x0b\x32\x1b.keter.DrugCandidate.Source\x1a(\n\x06Target\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x61\x66\x66inity\x18\x02 \x01(\x01\x1a\xc2\x01\n\x06Source\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\x04type\x18\x02 \x01(\x0e\x32 .keter.DrugCandidate.Source.Type\x12\x0f\n\x07version\x18\x03 \x01(\x11\x12\x0b\n\x03uri\x18\x04 \x01(\t\"\\\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05MODEL\x10\x01\x12\x0b\n\x07\x44\x41TASET\x10\x02\x12\x08\n\x04USER\x10\x03\x12\t\n\x05PAPER\x10\x04\x12\x0e\n\nEXPERIMENT\x10\x05\x12\n\n\x06SIFTER\x10\x06\x62\x06proto3'
)



_DRUGCANDIDATE_SOURCE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='keter.DrugCandidate.Source.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DATASET', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USER', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PAPER', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXPERIMENT', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SIFTER', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=403,
  serialized_end=495,
)
_sym_db.RegisterEnumDescriptor(_DRUGCANDIDATE_SOURCE_TYPE)


_DRUGCANDIDATE_TARGET = _descriptor.Descriptor(
  name='Target',
  full_name='keter.DrugCandidate.Target',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='keter.DrugCandidate.Target.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='affinity', full_name='keter.DrugCandidate.Target.affinity', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=298,
)

_DRUGCANDIDATE_SOURCE = _descriptor.Descriptor(
  name='Source',
  full_name='keter.DrugCandidate.Source',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='keter.DrugCandidate.Source.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='keter.DrugCandidate.Source.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='keter.DrugCandidate.Source.version', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uri', full_name='keter.DrugCandidate.Source.uri', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DRUGCANDIDATE_SOURCE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=495,
)

_DRUGCANDIDATE = _descriptor.Descriptor(
  name='DrugCandidate',
  full_name='keter.DrugCandidate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='keter.DrugCandidate.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='keter.DrugCandidate.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='smiles', full_name='keter.DrugCandidate.smiles', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drug_score', full_name='keter.DrugCandidate.drug_score', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='safety_score', full_name='keter.DrugCandidate.safety_score', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='manufacturability_score', full_name='keter.DrugCandidate.manufacturability_score', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targets', full_name='keter.DrugCandidate.targets', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sources', full_name='keter.DrugCandidate.sources', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DRUGCANDIDATE_TARGET, _DRUGCANDIDATE_SOURCE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=495,
)

_DRUGCANDIDATE_TARGET.containing_type = _DRUGCANDIDATE
_DRUGCANDIDATE_SOURCE.fields_by_name['type'].enum_type = _DRUGCANDIDATE_SOURCE_TYPE
_DRUGCANDIDATE_SOURCE.containing_type = _DRUGCANDIDATE
_DRUGCANDIDATE_SOURCE_TYPE.containing_type = _DRUGCANDIDATE_SOURCE
_DRUGCANDIDATE.fields_by_name['targets'].message_type = _DRUGCANDIDATE_TARGET
_DRUGCANDIDATE.fields_by_name['sources'].message_type = _DRUGCANDIDATE_SOURCE
DESCRIPTOR.message_types_by_name['DrugCandidate'] = _DRUGCANDIDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DrugCandidate = _reflection.GeneratedProtocolMessageType('DrugCandidate', (_message.Message,), {

  'Target' : _reflection.GeneratedProtocolMessageType('Target', (_message.Message,), {
    'DESCRIPTOR' : _DRUGCANDIDATE_TARGET,
    '__module__' : 'DrugCandidate_pb2'
    # @@protoc_insertion_point(class_scope:keter.DrugCandidate.Target)
    })
  ,

  'Source' : _reflection.GeneratedProtocolMessageType('Source', (_message.Message,), {
    'DESCRIPTOR' : _DRUGCANDIDATE_SOURCE,
    '__module__' : 'DrugCandidate_pb2'
    # @@protoc_insertion_point(class_scope:keter.DrugCandidate.Source)
    })
  ,
  'DESCRIPTOR' : _DRUGCANDIDATE,
  '__module__' : 'DrugCandidate_pb2'
  # @@protoc_insertion_point(class_scope:keter.DrugCandidate)
  })
_sym_db.RegisterMessage(DrugCandidate)
_sym_db.RegisterMessage(DrugCandidate.Target)
_sym_db.RegisterMessage(DrugCandidate.Source)


# @@protoc_insertion_point(module_scope)
